version: "3.9"
services:
  
  secp256k1-transmute:
    image: secp256k1-transmute
    build:
      context: ./suites/secp256k1-transmute
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  xmss-transmute:
    image: xmss-transmute
    build:
      context: ./suites/xmss-transmute
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  # dilithium-transmute:
  #   image: dilithium-transmute
  #   build:
  #     context: ./suites/dilithium-transmute
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./data:/data
  